### ISSUE TITLE
v1 todo list

### ISSUE THREAD

**Issue by starptr** [starptr/upe-blog#4]
The MVP isn't releasable (IMO). This issue tracks a list of things that's required before the website is public & official:

## Required

- [ ] UX for adding images #1
- [ ] Image captions #2

## Almost Required but can (should) be done after making the website official

- [ ] Code block syntax highlighting
- [ ] LaTeX
- [ ] Generate printable PDFs from a collection of articles #3
- [ ] Analytics #6 
- [ ] Clap count #5

## Optional (?)
- [ ] GFM features
- [ ] Light-Dark mode toggle
